# Generated by Django 5.1.4 on 2024-12-27 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_last_checked_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя проверка'),
        ),
    ]
